defaults:
  - _self_
  
## Romil + BT exp
hydra:
  run:
    dir: ${results_dir}
  sweep:
    dir: /home/mathiane/LNENWork/data_RoFormerMIL_CaA1CaA2_normdata_RoFormerMIL_CaA1CaA2_norm/dataRoFormer/results/${task}/${exp_name}/multirun  #data/results/${task}/${exp_name}/multirun ##
    #dir: data/results/${task}/${exp_name}/multirun
    subdir: ${hydra.job.override_dirname}

#features_dir: ${hydra:runtime.cwd}/data/features 
#split_dir: ${hydra:runtime.cwd}/data/splits
## Tumor segementation experiment
# features_dir: /home/mathiane/LNENWork/data_RoFormerMIL_CaA1CaA2_norm/dataRoFormer/features
# split_dir:  /home/mathiane/LNENWork/data_RoFormerMIL_CaA1CaA2_norm/dataRoFormer/splits 

## CaA1 vs CaA2
features_dir: /home/mathiane/LNENWork/data_RoFormerMIL_CaA1CaA2_norm/dataRoFormer/features 
split_dir:  /home/mathiane/LNENWork/data_RoFormerMIL_CaA1CaA2_norm/dataRoFormer/splits 

seed: 1

## Original
# hydra:
#   run:
#     dir: ${results_dir}
#   sweep:
#     dir: data/results/${task}/${exp_name}/multirun 
#     subdir: ${hydra.job.override_dirname}

# features_dir: ${hydra:runtime.cwd}/data/features 
# split_dir:  ${hydra:runtime.cwd}/data/splits 
# seed: 1


# Parameters copied from CLAM code
task_1_tumor_vs_normal:
  n_classes: 3
  MIL_Dataset:
    _target_: datasets.dataset_generic.Generic_MIL_Dataset
    csv_path: ${hydra:runtime.cwd}/dataset_csv/tumor_vs_normal_dummy_clean.csv
    data_dir: ${features_dir}
    shuffle: False
    seed: ${seed}
    print_info: True
    label_dict: {"normal_tissue": 0, "tumor_tissue": 1}
    patient_strat: False
    ignore: []


task_2_tumor_subtyping:
  n_classes: 2
  MIL_Dataset:
    _target_: datasets.dataset_generic.Generic_MIL_Dataset
    csv_path: ${features_dir}/slides_format.csv
    data_dir: ${features_dir}
    shuffle: False
    seed: ${seed}
    print_info: True
    label_dict: {"LUAD": 0, "LUSC": 1}
    patient_strat: False
    ignore: []
    h5_folder: 'h5_files_grid'


task_3_tumor_carcinoids_segmentation:
  n_classes: 2
  MIL_Dataset:
    _target_: datasets.dataset_generic.Generic_MIL_Dataset
    csv_path: ${features_dir}/slides_format.csv
    data_dir: ${features_dir}
    shuffle: False
    seed: ${seed}
    print_info: True
    label_dict: {"NonTumor": 0, "Tumor": 1}
    patient_strat: False
    ignore: []
    h5_folder: 'h5_files_grid'

task_4_carcinoids_CaA1_CaA2:
  n_classes: 2
  MIL_Dataset:
    _target_: CLAM.datasets.dataset_generic.Generic_MIL_Dataset
    csv_path: ${features_dir}/slides_format.csv
    data_dir: ${features_dir}
    shuffle: False
    seed: ${seed}
    print_info: True
    label_dict: {"CaA1": 0, "CaA2": 1}
    patient_strat: False
    ignore: []
    h5_folder: 'h5_files_grid'

task_5_carcinoids_TCAC:
  n_classes: 2
  MIL_Dataset:
    _target_: CLAM.datasets.dataset_generic.Generic_MIL_Dataset
    csv_path: ${features_dir}/slides_format.csv
    data_dir: ${features_dir}
    shuffle: False
    seed: ${seed}
    print_info: True
    label_dict: {"TC": 0, "AC": 1}
    patient_strat: False
    ignore: []
    h5_folder: 'h5_files_grid'