defaults:
  - defaults
  - model_dict@model_dict
  - _self_ 

task: task_4_carcinoids_CaA1_CaA2
exp_name: CaA1Ca2_unbalanced_norm

model_type: BTRoPEAMIL_s_pixel

label_frac: 100

split: test

results_dir: /home/mathiane/LNENWork/data_RoFormerMIL_CaA1CaA2_norm/dataRoFormer/results/${task}/${exp_name}/label_frac=${label_frac}/${model_type}/eval/${now:%Y-%m-%d}_${now:%H-%M-%S}
tracking_uri: ${hydra:runtime.cwd}/data/mlflow
load_model_from_mlflow: False

ckpt_path: "/home/mathiane/LNENWork/data_RoFormerMIL_CaA1CaA2_norm/dataRoFormer/results/task_4_carcinoids_CaA1_CaA2/CaA1Ca2_unbalanced_norm/label_frac=100/BTRoPEAMIL_s_pixel/training/2024-04-11_21-24-30/checkpoints"
mlflow:
  run_id: "/home/mathiane/LNENWork/DDS_roformer/DDS-RoFormerMIL/mlartifacts/347347552193334047/31792c9d35974ab3bccffb830786db6f/artifacts/fold_0/best.ckpt" #e667c13579f64986ae5c2a9501b1a79d

lightning_module:
  _target_: romil.models.lightning_modules.MILLitModule

  attn_scores: True
  
  model: ${model_dict.${model_type}}

  loss :
    _target_: torch.nn.CrossEntropyLoss

  optimizer: 
  use_instance_loss: False

  bag_loss_weight: 0.7
  
k_folds:
  k_start: 20
  k_end: 21


multiclass_avg: "weighted"
