defaults:
  - defaults
  - model_dict@model_dict
  - _self_ 

task: task_3_tumor_carcinoids_segmentation
exp_name: debug

model_type: BTRoPEAMIL_s_pixel

label_frac: 100

split: train #val #test

#results_dir: ${hydra:runtime.cwd}/data/results/${task}/${exp_name}/label_frac=${label_frac}/${model_type}/eval/${now:%Y-%m-%d}_${now:%H-%M-%S}
results_dir: /home/mathiane/LNENWork/data_RoFormerMIL_TumorSegExp/dataRoFormer/results/${task}/${exp_name}/label_frac=${label_frac}/${model_type}/eval/${now:%Y-%m-%d}_${now:%H-%M-%S}
#_uri: ${hydra:runtime.cwd}/data/mlflow
tracking_uri:  /home/mathiane/LNENWork/data_RoFormerMIL_TumorSegExp/dataRoFormer/mlflow
load_model_from_mlflow: False

ckpt_path: /home/mathiane/LNENWork/data_RoFormerMIL_TumorSegExp/dataRoFormer/results/task_3_tumor_carcinoids_segmentation/debug/label_frac=100/BTRoPEAMIL_s_pixel/training/2024-02-23_17-05-47/checkpoints
mlflow:
  run_id: efa5efa7cb4345278ea0ea8e5f786767

lightning_module:
  _target_: romil.models.lightning_modules.MILLitModule

  attn_scores: True
  
  model: ${model_dict.${model_type}}

  loss :
    _target_: torch.nn.CrossEntropyLoss

  optimizer: 
  use_instance_loss: False

  bag_loss_weight: 0.7
  
k_folds:
  k_start: 0
  k_end: 15


multiclass_avg: "weighted"
